### ISSUE TITLE
Ellipsizing

### ISSUE THREAD

**Issue by Jake-Piatkowski** [neopixl/PixlUI#12]
Hi, I'm using your TextViews mostly for the ease of applying custom fonts - they work great :)

However, I've got a small problem now: how can I properly ellipsize my text? I put a long string into a TextView, e.g. "Twig 0000000000000000000000000000" and whatever I've tried, I'd always get "Twig..." - regardless of the type of ellipsizing I specified in the XML code. 
Is that the intended behaviour or am I missing something? Maybe I should be using the EllipsizingTextView class?

Just in case, here's my code for the TextView:
```XML
<com.neopixl.pixlui.components.textview.TextView
        android:id="@+id/listview_item_title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:layout_marginRight="10dp"
        android:layout_marginTop="20dp"
        android:layout_toRightOf="@+id/listview_item_thumbnail"
        android:maxLines="1"
        android:textAllCaps="true"
        android:textColor="@android:color/black"
        android:textSize="30sp"
        pixlui:typeface="DIN Condensed Bold.otf" />
```

**Comment by Ahsan-SDSol** [comment]
Hi odemolliens, when will we expect the next release ?

**Comment by odemolliens** [comment]
in the coming month :)

**Comment by odemolliens** [comment]
1.0.6: *EllipsizingTextView* is now removed from *com.neopixl.pixlui.components.textview*

How it's now guys?
