### ISSUE TITLE
Using string resource as typeface

### ISSUE THREAD

**Issue by Jake-Piatkowski** [neopixl/PixlUI#15]
Is it possible to use a string resource as the typeface?

For example instead of this:
```android
pixlui:typeface="GillSansStd BoldCondensed.otf"
```
I'd prefer to do this:
```android
pixlui:typeface="@string/font1"
```
and somewhere else in my XML value resource files:
```android
<string name="font1">GillSansStd BoldCondensed.otf</string>
```

Currently it seems that if I try to do this, the typeface doesn't get set at all - I get the following message: `Could not get typeface: native typeface cannot be made with name: @string/font1`.

Is there any chance of me achieving the effect I need?

**Comment by odemolliens** [comment]
I will include style / string in the next release !

Nothing ready in /dev/ branch for the moment

**Comment by odemolliens** [comment]
The only current way to do that is to override in each custom components this methods
```
private void setCustomFont(Context ctx, AttributeSet attrs) {
String typefaceName = attrs.getAttributeValue(
PixlUIContants.SCHEMA_URL, EDITTEXT_ATTRIBUTE_FONT_NAME);
if (typefaceName != null) {
setPaintFlags(this.getPaintFlags() | Paint.SUBPIXEL_TEXT_FLAG
| Paint.LINEAR_TEXT_FLAG);
setCustomFont(ctx, typefaceName);
}
}
```
the var "attrs" contains your ```"@string/font1"```

**Comment by Jake-Piatkowski** [comment]
Thanks :)

**Comment by odemolliens** [comment]
On last version available on master

You can use:

```style="@style/AppTheme.TextOswaldRegular"```
