### ISSUE TITLE
adapt the new lib

### ISSUE THREAD

**Issue by jjhesk** [neopixl/PixlUI#20]
is that possible to adapte this [lib](https://github.com/Kianoni/android-fontloading-textview) that will make the capability of font loading in style xml possible?

**Comment by odemolliens** [comment]
you can already do that on last version on master branch

**Comment by jjhesk** [comment]
i see. how does it work? are there any examples?

**Comment by odemolliens** [comment]
As a library project
Take a look on XML:
https://github.com/neopixl/PixlUI/blob/master/Sample/res/layout/activity_main.xml
