### ISSUE TITLE
jitpack issue

### ISSUE THREAD

**Issue by jjhesk** [neopixl/PixlUI#21]
jitpack is not working on 1.0.5. Can you fix that?

**Comment by jitpack-io** [comment]
there was no build file in 1.0.5. Perhaps a new release can be made

**Comment by odemolliens** [comment]
done

**Comment by jitpack-io** [comment]
@odemolliens Was there a new release in https://github.com/neopixl/PixlUI/releases? Perhaps not appearing on GH for me due to the ddos attack.

**Comment by odemolliens** [comment]
I currently working on the 1.0.6 version. I will make a release in coming weeks.

I don't have change something on https://github.com/neopixl/PixlUI/releases

**Comment by odemolliens** [comment]
I don't have really understand why 1.0.5 was not working on jitpack website

**Comment by jitpack-io** [comment]
Well there was no build.gradle file when v1.0.5 tag was made. This is how the project was at 1.0.5 https://github.com/neopixl/PixlUI/tree/v1.0.5. JitPack check's out code at that version and tries to find any build files.

**Comment by odemolliens** [comment]
You have totally right.
I have start to migrate eclipse project to gradle project (Android studio).

I will made a new release asap

**Comment by jitpack-io** [comment]
Nice! Cool stuff!

**Comment by jjhesk** [comment]
+1

**Comment by odemolliens** [comment]
@jitpack-io 

How to configure jitpack to say:
Version <=1.0.5 jar project - eclispe
Version >1.0.5 gradle - library project - gradle

**Comment by jitpack-io** [comment]
@odemolliens We currently don't support version ranges. Why no use exact version?
