### ISSUE TITLE
Project unavailable on jitpack.io

### ISSUE THREAD

**Issue by Trowa** [neopixl/PixlUI#23]
Hello,

It seems that your library is not working on jetpack.io so the only way to use it is to add the .jar to a project but this way it is impossible to define a style with custom font. Could you add it to jetpack please ?

**Comment by jitpack-io** [comment]
@Trowa This should work: https://jitpack.io/#neopixl/PixlUI/v1.0.5a

**Comment by Trowa** [comment]
It works fine now, thanks :)
