### ISSUE TITLE
Fonts don't get selected

### ISSUE THREAD

**Issue by vijaykd** [neopixl/PixlUI#28]
I am trying out similar to sample project:

<com.neopixl.pixlui.components.textview.TextView
                android:id="@+id/loadingtext"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="@string/loadingtext"
                android:textColor="@drawable/text_selector_listview"
                android:paddingTop="3dp"
                android:layout_gravity="center"
                pixlui:clearclipboardcontent="true"
                pixlui:copyandpaste="false"
                style="@style/TextRoboto.t1"

<style name="TextRoboto.t1" parent="MyMaterialTheme.Base">
        <item name="typeface">Roboto-Regular.ttf</item>
        <item name="android:textSize">11sp</item>
    </style>

XML shows: Asset not found: fonts/Roboto-Regular.ttf

I can confirm the file is there in assets/fonts folder (Assets folder is in main Folder and not inside res folder)

What could be wrong?

**Comment by odemolliens** [comment]
Can you take a look there : [http://stackoverflow.com/a/35450511/1176412](http://stackoverflow.com/a/35450511/1176412)

**Comment by vijaykd** [comment]
I have tried this already. Didn't work for me.. still the same. :(

**Comment by odemolliens** [comment]
Do you see the font on the simulator/device ?

**Comment by odemolliens** [comment]
No news
