### ISSUE TITLE
Memory Leak: Activity Leak on PixlUIfaceManager.INSTANCE

### ISSUE THREAD

**Issue by jackcsk** [neopixl/PixlUI#31]
PixlUIfaceManager.INSTANCE holds reference of the first activity using the widgets, and causing memory leak. (Activity is not released properly)

There are 2 options to address this issue:
  * Call PixlUIfaceManager.getInstance(applicationContext) in Application class, or
  * modify the class to reference to application context.

Which one would you prefer?

**Comment by neopixl** [comment]
Thanks @jackcsk.

We will reference the application context in PixlUIfaceManager (second option).
