### ISSUE TITLE
Add to Maven

### ISSUE THREAD

**Issue by gaudecker** [neopixl/PixlUI#7]
It would be helpful to just add the dependency from Maven.

**Comment by BenGroot** [comment]
Is it in Maven yet?

**Comment by neopixl** [comment]
Hi Ben,

not yet. I will try to look at it next week.

regards,

**Comment by ararog** [comment]
I was about to request gradle support, but once it is on maven I'll be simple to use on gradle build script too and make PixUI more Android Studio friendly.

**Comment by odemolliens** [comment]
Maven Setup
==========

Add Repository
```xml
<repository>
	    <id>jitpack.io</id>
	    <url>https://jitpack.io</url>
	</repository>

```
Add Dependency:
```xml
	<dependency>
	    <groupId>com.github.neopixl</groupId>
	    <artifactId>PixlUI</artifactId>
	    <version>v1.0.5</version>
	</dependency>

**Comment by BenGroot** [comment]
Awesome guys, Thanks!
